// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/razpravljalnica.proto

package razpravljalnica

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OpType int32

const (
	OpType_OP_POST OpType = 0 // add a message to a topic
	OpType_OP_LIKE OpType = 1 // like a message
)

// Enum value maps for OpType.
var (
	OpType_name = map[int32]string{
		0: "OP_POST",
		1: "OP_LIKE",
	}
	OpType_value = map[string]int32{
		"OP_POST": 0,
		"OP_LIKE": 1,
	}
)

func (x OpType) Enum() *OpType {
	p := new(OpType)
	*p = x
	return p
}

func (x OpType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OpType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_razpravljalnica_proto_enumTypes[0].Descriptor()
}

func (OpType) Type() protoreflect.EnumType {
	return &file_proto_razpravljalnica_proto_enumTypes[0]
}

func (x OpType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OpType.Descriptor instead.
func (OpType) EnumDescriptor() ([]byte, []int) {
	return file_proto_razpravljalnica_proto_rawDescGZIP(), []int{0}
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_proto_razpravljalnica_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_proto_razpravljalnica_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_proto_razpravljalnica_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Topic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Topic) Reset() {
	*x = Topic{}
	mi := &file_proto_razpravljalnica_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Topic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Topic) ProtoMessage() {}

func (x *Topic) ProtoReflect() protoreflect.Message {
	mi := &file_proto_razpravljalnica_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Topic.ProtoReflect.Descriptor instead.
func (*Topic) Descriptor() ([]byte, []int) {
	return file_proto_razpravljalnica_proto_rawDescGZIP(), []int{1}
}

func (x *Topic) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Topic) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TopicId       int64                  `protobuf:"varint,2,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Likes         int32                  `protobuf:"varint,6,opt,name=likes,proto3" json:"likes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_proto_razpravljalnica_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto_razpravljalnica_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_proto_razpravljalnica_proto_rawDescGZIP(), []int{2}
}

func (x *Message) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Message) GetTopicId() int64 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

func (x *Message) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Message) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Message) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Message) GetLikes() int32 {
	if x != nil {
		return x.Likes
	}
	return 0
}

type Like struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicId       int64                  `protobuf:"varint,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	MessageId     int64                  `protobuf:"varint,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // user who liked the message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Like) Reset() {
	*x = Like{}
	mi := &file_proto_razpravljalnica_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Like) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Like) ProtoMessage() {}

func (x *Like) ProtoReflect() protoreflect.Message {
	mi := &file_proto_razpravljalnica_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Like.ProtoReflect.Descriptor instead.
func (*Like) Descriptor() ([]byte, []int) {
	return file_proto_razpravljalnica_proto_rawDescGZIP(), []int{3}
}

func (x *Like) GetTopicId() int64 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

func (x *Like) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *Like) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type NodeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_proto_razpravljalnica_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_razpravljalnica_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_proto_razpravljalnica_proto_rawDescGZIP(), []int{4}
}

func (x *NodeInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type UserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          []*User                `protobuf:"bytes,1,rep,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserResponse) Reset() {
	*x = UserResponse{}
	mi := &file_proto_razpravljalnica_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponse) ProtoMessage() {}

func (x *UserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_razpravljalnica_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponse.ProtoReflect.Descriptor instead.
func (*UserResponse) Descriptor() ([]byte, []int) {
	return file_proto_razpravljalnica_proto_rawDescGZIP(), []int{5}
}

func (x *UserResponse) GetUser() []*User {
	if x != nil {
		return x.User
	}
	return nil
}

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_proto_razpravljalnica_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_razpravljalnica_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_razpravljalnica_proto_rawDescGZIP(), []int{6}
}

func (x *CreateUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateTopicRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTopicRequest) Reset() {
	*x = CreateTopicRequest{}
	mi := &file_proto_razpravljalnica_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTopicRequest) ProtoMessage() {}

func (x *CreateTopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_razpravljalnica_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTopicRequest.ProtoReflect.Descriptor instead.
func (*CreateTopicRequest) Descriptor() ([]byte, []int) {
	return file_proto_razpravljalnica_proto_rawDescGZIP(), []int{7}
}

func (x *CreateTopicRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type PostMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicId       int64                  `protobuf:"varint,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostMessageRequest) Reset() {
	*x = PostMessageRequest{}
	mi := &file_proto_razpravljalnica_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostMessageRequest) ProtoMessage() {}

func (x *PostMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_razpravljalnica_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostMessageRequest.ProtoReflect.Descriptor instead.
func (*PostMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_razpravljalnica_proto_rawDescGZIP(), []int{8}
}

func (x *PostMessageRequest) GetTopicId() int64 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

func (x *PostMessageRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PostMessageRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type LikeMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicId       int64                  `protobuf:"varint,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	MessageId     int64                  `protobuf:"varint,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // user who posted the like
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeMessageRequest) Reset() {
	*x = LikeMessageRequest{}
	mi := &file_proto_razpravljalnica_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeMessageRequest) ProtoMessage() {}

func (x *LikeMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_razpravljalnica_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeMessageRequest.ProtoReflect.Descriptor instead.
func (*LikeMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_razpravljalnica_proto_rawDescGZIP(), []int{9}
}

func (x *LikeMessageRequest) GetTopicId() int64 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

func (x *LikeMessageRequest) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *LikeMessageRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ListTopicsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topics        []*Topic               `protobuf:"bytes,1,rep,name=topics,proto3" json:"topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTopicsResponse) Reset() {
	*x = ListTopicsResponse{}
	mi := &file_proto_razpravljalnica_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTopicsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTopicsResponse) ProtoMessage() {}

func (x *ListTopicsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_razpravljalnica_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTopicsResponse.ProtoReflect.Descriptor instead.
func (*ListTopicsResponse) Descriptor() ([]byte, []int) {
	return file_proto_razpravljalnica_proto_rawDescGZIP(), []int{10}
}

func (x *ListTopicsResponse) GetTopics() []*Topic {
	if x != nil {
		return x.Topics
	}
	return nil
}

type GetMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicId       int64                  `protobuf:"varint,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	FromMessageId int64                  `protobuf:"varint,2,opt,name=from_message_id,json=fromMessageId,proto3" json:"from_message_id,omitempty"` // starting id of the message (0 from beggining)
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`                                        // max number of messages
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesRequest) Reset() {
	*x = GetMessagesRequest{}
	mi := &file_proto_razpravljalnica_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesRequest) ProtoMessage() {}

func (x *GetMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_razpravljalnica_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesRequest.ProtoReflect.Descriptor instead.
func (*GetMessagesRequest) Descriptor() ([]byte, []int) {
	return file_proto_razpravljalnica_proto_rawDescGZIP(), []int{11}
}

func (x *GetMessagesRequest) GetTopicId() int64 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

func (x *GetMessagesRequest) GetFromMessageId() int64 {
	if x != nil {
		return x.FromMessageId
	}
	return 0
}

func (x *GetMessagesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesResponse) Reset() {
	*x = GetMessagesResponse{}
	mi := &file_proto_razpravljalnica_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesResponse) ProtoMessage() {}

func (x *GetMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_razpravljalnica_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesResponse.ProtoReflect.Descriptor instead.
func (*GetMessagesResponse) Descriptor() ([]byte, []int) {
	return file_proto_razpravljalnica_proto_rawDescGZIP(), []int{12}
}

func (x *GetMessagesResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

type SubscribeTopicRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TopicId        []int64                `protobuf:"varint,1,rep,packed,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	UserId         int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FromMessageId  int64                  `protobuf:"varint,3,opt,name=from_message_id,json=fromMessageId,proto3" json:"from_message_id,omitempty"` // starting id of the message
	SubscribeToken string                 `protobuf:"bytes,4,opt,name=subscribe_token,json=subscribeToken,proto3" json:"subscribe_token,omitempty"` // token generated by the head used to authorize the subscription
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubscribeTopicRequest) Reset() {
	*x = SubscribeTopicRequest{}
	mi := &file_proto_razpravljalnica_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeTopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeTopicRequest) ProtoMessage() {}

func (x *SubscribeTopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_razpravljalnica_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeTopicRequest.ProtoReflect.Descriptor instead.
func (*SubscribeTopicRequest) Descriptor() ([]byte, []int) {
	return file_proto_razpravljalnica_proto_rawDescGZIP(), []int{13}
}

func (x *SubscribeTopicRequest) GetTopicId() []int64 {
	if x != nil {
		return x.TopicId
	}
	return nil
}

func (x *SubscribeTopicRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SubscribeTopicRequest) GetFromMessageId() int64 {
	if x != nil {
		return x.FromMessageId
	}
	return 0
}

func (x *SubscribeTopicRequest) GetSubscribeToken() string {
	if x != nil {
		return x.SubscribeToken
	}
	return ""
}

type SubscriptionNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TopicId       []int64                `protobuf:"varint,2,rep,packed,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriptionNodeRequest) Reset() {
	*x = SubscriptionNodeRequest{}
	mi := &file_proto_razpravljalnica_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionNodeRequest) ProtoMessage() {}

func (x *SubscriptionNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_razpravljalnica_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionNodeRequest.ProtoReflect.Descriptor instead.
func (*SubscriptionNodeRequest) Descriptor() ([]byte, []int) {
	return file_proto_razpravljalnica_proto_rawDescGZIP(), []int{14}
}

func (x *SubscriptionNodeRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SubscriptionNodeRequest) GetTopicId() []int64 {
	if x != nil {
		return x.TopicId
	}
	return nil
}

type SubscriptionNodeResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscribeToken string                 `protobuf:"bytes,1,opt,name=subscribe_token,json=subscribeToken,proto3" json:"subscribe_token,omitempty"` // subscription token to be presented to the returned node
	Node           *NodeInfo              `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubscriptionNodeResponse) Reset() {
	*x = SubscriptionNodeResponse{}
	mi := &file_proto_razpravljalnica_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionNodeResponse) ProtoMessage() {}

func (x *SubscriptionNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_razpravljalnica_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionNodeResponse.ProtoReflect.Descriptor instead.
func (*SubscriptionNodeResponse) Descriptor() ([]byte, []int) {
	return file_proto_razpravljalnica_proto_rawDescGZIP(), []int{15}
}

func (x *SubscriptionNodeResponse) GetSubscribeToken() string {
	if x != nil {
		return x.SubscribeToken
	}
	return ""
}

func (x *SubscriptionNodeResponse) GetNode() *NodeInfo {
	if x != nil {
		return x.Node
	}
	return nil
}

type MessageEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SequenceNumber int64                  `protobuf:"varint,1,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"` // monotonically increasing event number
	Op             OpType                 `protobuf:"varint,2,opt,name=op,proto3,enum=proto.OpType" json:"op,omitempty"`                             // type of event
	Message        *Message               `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	EventAt        *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=event_at,json=eventAt,proto3" json:"event_at,omitempty"` // timestamp of the event
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MessageEvent) Reset() {
	*x = MessageEvent{}
	mi := &file_proto_razpravljalnica_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageEvent) ProtoMessage() {}

func (x *MessageEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_razpravljalnica_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageEvent.ProtoReflect.Descriptor instead.
func (*MessageEvent) Descriptor() ([]byte, []int) {
	return file_proto_razpravljalnica_proto_rawDescGZIP(), []int{16}
}

func (x *MessageEvent) GetSequenceNumber() int64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *MessageEvent) GetOp() OpType {
	if x != nil {
		return x.Op
	}
	return OpType_OP_POST
}

func (x *MessageEvent) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *MessageEvent) GetEventAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EventAt
	}
	return nil
}

type NewServerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SyncServer    *NodeInfo              `protobuf:"bytes,1,opt,name=sync_server,json=syncServer,proto3" json:"sync_server,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewServerResponse) Reset() {
	*x = NewServerResponse{}
	mi := &file_proto_razpravljalnica_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewServerResponse) ProtoMessage() {}

func (x *NewServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_razpravljalnica_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewServerResponse.ProtoReflect.Descriptor instead.
func (*NewServerResponse) Descriptor() ([]byte, []int) {
	return file_proto_razpravljalnica_proto_rawDescGZIP(), []int{17}
}

func (x *NewServerResponse) GetSyncServer() *NodeInfo {
	if x != nil {
		return x.SyncServer
	}
	return nil
}

type NextServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NextServer    *NodeInfo              `protobuf:"bytes,1,opt,name=next_server,json=nextServer,proto3" json:"next_server,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NextServerRequest) Reset() {
	*x = NextServerRequest{}
	mi := &file_proto_razpravljalnica_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NextServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NextServerRequest) ProtoMessage() {}

func (x *NextServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_razpravljalnica_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NextServerRequest.ProtoReflect.Descriptor instead.
func (*NextServerRequest) Descriptor() ([]byte, []int) {
	return file_proto_razpravljalnica_proto_rawDescGZIP(), []int{18}
}

func (x *NextServerRequest) GetNextServer() *NodeInfo {
	if x != nil {
		return x.NextServer
	}
	return nil
}

type NewServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewServer     *NodeInfo              `protobuf:"bytes,1,opt,name=new_server,json=newServer,proto3" json:"new_server,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewServerRequest) Reset() {
	*x = NewServerRequest{}
	mi := &file_proto_razpravljalnica_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewServerRequest) ProtoMessage() {}

func (x *NewServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_razpravljalnica_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewServerRequest.ProtoReflect.Descriptor instead.
func (*NewServerRequest) Descriptor() ([]byte, []int) {
	return file_proto_razpravljalnica_proto_rawDescGZIP(), []int{19}
}

func (x *NewServerRequest) GetNewServer() *NodeInfo {
	if x != nil {
		return x.NewServer
	}
	return nil
}

type SetTailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tail          bool                   `protobuf:"varint,1,opt,name=tail,proto3" json:"tail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTailRequest) Reset() {
	*x = SetTailRequest{}
	mi := &file_proto_razpravljalnica_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTailRequest) ProtoMessage() {}

func (x *SetTailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_razpravljalnica_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTailRequest.ProtoReflect.Descriptor instead.
func (*SetTailRequest) Descriptor() ([]byte, []int) {
	return file_proto_razpravljalnica_proto_rawDescGZIP(), []int{20}
}

func (x *SetTailRequest) GetTail() bool {
	if x != nil {
		return x.Tail
	}
	return false
}

type SetHeadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Head          bool                   `protobuf:"varint,1,opt,name=head,proto3" json:"head,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetHeadRequest) Reset() {
	*x = SetHeadRequest{}
	mi := &file_proto_razpravljalnica_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetHeadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetHeadRequest) ProtoMessage() {}

func (x *SetHeadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_razpravljalnica_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetHeadRequest.ProtoReflect.Descriptor instead.
func (*SetHeadRequest) Descriptor() ([]byte, []int) {
	return file_proto_razpravljalnica_proto_rawDescGZIP(), []int{21}
}

func (x *SetHeadRequest) GetHead() bool {
	if x != nil {
		return x.Head
	}
	return false
}

type GetClusterStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Head          *NodeInfo              `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"`
	Tail          *NodeInfo              `protobuf:"bytes,2,opt,name=tail,proto3" json:"tail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClusterStateResponse) Reset() {
	*x = GetClusterStateResponse{}
	mi := &file_proto_razpravljalnica_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClusterStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClusterStateResponse) ProtoMessage() {}

func (x *GetClusterStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_razpravljalnica_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClusterStateResponse.ProtoReflect.Descriptor instead.
func (*GetClusterStateResponse) Descriptor() ([]byte, []int) {
	return file_proto_razpravljalnica_proto_rawDescGZIP(), []int{22}
}

func (x *GetClusterStateResponse) GetHead() *NodeInfo {
	if x != nil {
		return x.Head
	}
	return nil
}

func (x *GetClusterStateResponse) GetTail() *NodeInfo {
	if x != nil {
		return x.Tail
	}
	return nil
}

type SyncUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncUserRequest) Reset() {
	*x = SyncUserRequest{}
	mi := &file_proto_razpravljalnica_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncUserRequest) ProtoMessage() {}

func (x *SyncUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_razpravljalnica_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncUserRequest.ProtoReflect.Descriptor instead.
func (*SyncUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_razpravljalnica_proto_rawDescGZIP(), []int{23}
}

func (x *SyncUserRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SyncUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SyncTopicRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncTopicRequest) Reset() {
	*x = SyncTopicRequest{}
	mi := &file_proto_razpravljalnica_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncTopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncTopicRequest) ProtoMessage() {}

func (x *SyncTopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_razpravljalnica_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncTopicRequest.ProtoReflect.Descriptor instead.
func (*SyncTopicRequest) Descriptor() ([]byte, []int) {
	return file_proto_razpravljalnica_proto_rawDescGZIP(), []int{24}
}

func (x *SyncTopicRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SyncTopicRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SyncMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicId       int64                  `protobuf:"varint,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	PostId        int64                  `protobuf:"varint,2,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Post          *Message               `protobuf:"bytes,3,opt,name=post,proto3" json:"post,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncMessageRequest) Reset() {
	*x = SyncMessageRequest{}
	mi := &file_proto_razpravljalnica_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncMessageRequest) ProtoMessage() {}

func (x *SyncMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_razpravljalnica_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncMessageRequest.ProtoReflect.Descriptor instead.
func (*SyncMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_razpravljalnica_proto_rawDescGZIP(), []int{25}
}

func (x *SyncMessageRequest) GetTopicId() int64 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

func (x *SyncMessageRequest) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *SyncMessageRequest) GetPost() *Message {
	if x != nil {
		return x.Post
	}
	return nil
}

type SyncLikeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     int64                  `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TopicId       int64                  `protobuf:"varint,3,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncLikeRequest) Reset() {
	*x = SyncLikeRequest{}
	mi := &file_proto_razpravljalnica_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncLikeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncLikeRequest) ProtoMessage() {}

func (x *SyncLikeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_razpravljalnica_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncLikeRequest.ProtoReflect.Descriptor instead.
func (*SyncLikeRequest) Descriptor() ([]byte, []int) {
	return file_proto_razpravljalnica_proto_rawDescGZIP(), []int{26}
}

func (x *SyncLikeRequest) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *SyncLikeRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SyncLikeRequest) GetTopicId() int64 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

type TopicPosts struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicId       int64                  `protobuf:"varint,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	Posts         map[int64]*Message     `protobuf:"bytes,2,rep,name=posts,proto3" json:"posts,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // postId -> Message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopicPosts) Reset() {
	*x = TopicPosts{}
	mi := &file_proto_razpravljalnica_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicPosts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicPosts) ProtoMessage() {}

func (x *TopicPosts) ProtoReflect() protoreflect.Message {
	mi := &file_proto_razpravljalnica_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicPosts.ProtoReflect.Descriptor instead.
func (*TopicPosts) Descriptor() ([]byte, []int) {
	return file_proto_razpravljalnica_proto_rawDescGZIP(), []int{27}
}

func (x *TopicPosts) GetTopicId() int64 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

func (x *TopicPosts) GetPosts() map[int64]*Message {
	if x != nil {
		return x.Posts
	}
	return nil
}

type TopicPostsList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicId       int64                  `protobuf:"varint,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	Posts         []*Message             `protobuf:"bytes,2,rep,name=posts,proto3" json:"posts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopicPostsList) Reset() {
	*x = TopicPostsList{}
	mi := &file_proto_razpravljalnica_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicPostsList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicPostsList) ProtoMessage() {}

func (x *TopicPostsList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_razpravljalnica_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicPostsList.ProtoReflect.Descriptor instead.
func (*TopicPostsList) Descriptor() ([]byte, []int) {
	return file_proto_razpravljalnica_proto_rawDescGZIP(), []int{28}
}

func (x *TopicPostsList) GetTopicId() int64 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

func (x *TopicPostsList) GetPosts() []*Message {
	if x != nil {
		return x.Posts
	}
	return nil
}

type UserLikes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MessageIds    []int64                `protobuf:"varint,2,rep,packed,name=message_ids,json=messageIds,proto3" json:"message_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLikes) Reset() {
	*x = UserLikes{}
	mi := &file_proto_razpravljalnica_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLikes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLikes) ProtoMessage() {}

func (x *UserLikes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_razpravljalnica_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLikes.ProtoReflect.Descriptor instead.
func (*UserLikes) Descriptor() ([]byte, []int) {
	return file_proto_razpravljalnica_proto_rawDescGZIP(), []int{29}
}

func (x *UserLikes) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserLikes) GetMessageIds() []int64 {
	if x != nil {
		return x.MessageIds
	}
	return nil
}

type SubscriptionData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicName     string                 `protobuf:"bytes,1,opt,name=topic_name,json=topicName,proto3" json:"topic_name,omitempty"`
	TopicId       int64                  `protobuf:"varint,2,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriptionData) Reset() {
	*x = SubscriptionData{}
	mi := &file_proto_razpravljalnica_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionData) ProtoMessage() {}

func (x *SubscriptionData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_razpravljalnica_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionData.ProtoReflect.Descriptor instead.
func (*SubscriptionData) Descriptor() ([]byte, []int) {
	return file_proto_razpravljalnica_proto_rawDescGZIP(), []int{30}
}

func (x *SubscriptionData) GetTopicName() string {
	if x != nil {
		return x.TopicName
	}
	return ""
}

func (x *SubscriptionData) GetTopicId() int64 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

type UserSubscriptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Subscriptions []*SubscriptionData    `protobuf:"bytes,2,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserSubscriptions) Reset() {
	*x = UserSubscriptions{}
	mi := &file_proto_razpravljalnica_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSubscriptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSubscriptions) ProtoMessage() {}

func (x *UserSubscriptions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_razpravljalnica_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSubscriptions.ProtoReflect.Descriptor instead.
func (*UserSubscriptions) Descriptor() ([]byte, []int) {
	return file_proto_razpravljalnica_proto_rawDescGZIP(), []int{31}
}

func (x *UserSubscriptions) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserSubscriptions) GetSubscriptions() []*SubscriptionData {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

type SyncServerResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Users             map[string]int64       `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	UserIndex         int64                  `protobuf:"varint,2,opt,name=user_index,json=userIndex,proto3" json:"user_index,omitempty"`
	Topics            map[string]int64       `protobuf:"bytes,3,rep,name=topics,proto3" json:"topics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	TopicIndex        int64                  `protobuf:"varint,4,opt,name=topic_index,json=topicIndex,proto3" json:"topic_index,omitempty"`
	TopicsPosts       []*TopicPosts          `protobuf:"bytes,5,rep,name=topics_posts,json=topicsPosts,proto3" json:"topics_posts,omitempty"`
	TopicsPostsList   []*TopicPostsList      `protobuf:"bytes,6,rep,name=topics_posts_list,json=topicsPostsList,proto3" json:"topics_posts_list,omitempty"`
	PostIndex         int64                  `protobuf:"varint,7,opt,name=post_index,json=postIndex,proto3" json:"post_index,omitempty"`
	UserLikes         []*UserLikes           `protobuf:"bytes,8,rep,name=user_likes,json=userLikes,proto3" json:"user_likes,omitempty"`
	UserSubscriptions []*UserSubscriptions   `protobuf:"bytes,9,rep,name=user_subscriptions,json=userSubscriptions,proto3" json:"user_subscriptions,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SyncServerResponse) Reset() {
	*x = SyncServerResponse{}
	mi := &file_proto_razpravljalnica_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncServerResponse) ProtoMessage() {}

func (x *SyncServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_razpravljalnica_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncServerResponse.ProtoReflect.Descriptor instead.
func (*SyncServerResponse) Descriptor() ([]byte, []int) {
	return file_proto_razpravljalnica_proto_rawDescGZIP(), []int{32}
}

func (x *SyncServerResponse) GetUsers() map[string]int64 {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *SyncServerResponse) GetUserIndex() int64 {
	if x != nil {
		return x.UserIndex
	}
	return 0
}

func (x *SyncServerResponse) GetTopics() map[string]int64 {
	if x != nil {
		return x.Topics
	}
	return nil
}

func (x *SyncServerResponse) GetTopicIndex() int64 {
	if x != nil {
		return x.TopicIndex
	}
	return 0
}

func (x *SyncServerResponse) GetTopicsPosts() []*TopicPosts {
	if x != nil {
		return x.TopicsPosts
	}
	return nil
}

func (x *SyncServerResponse) GetTopicsPostsList() []*TopicPostsList {
	if x != nil {
		return x.TopicsPostsList
	}
	return nil
}

func (x *SyncServerResponse) GetPostIndex() int64 {
	if x != nil {
		return x.PostIndex
	}
	return 0
}

func (x *SyncServerResponse) GetUserLikes() []*UserLikes {
	if x != nil {
		return x.UserLikes
	}
	return nil
}

func (x *SyncServerResponse) GetUserSubscriptions() []*UserSubscriptions {
	if x != nil {
		return x.UserSubscriptions
	}
	return nil
}

var File_proto_razpravljalnica_proto protoreflect.FileDescriptor

const file_proto_razpravljalnica_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/razpravljalnica.proto\x12\x05proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"*\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"+\n" +
	"\x05Topic\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xb2\x01\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\btopic_id\x18\x02 \x01(\x03R\atopicId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x14\n" +
	"\x05likes\x18\x06 \x01(\x05R\x05likes\"Y\n" +
	"\x04Like\x12\x19\n" +
	"\btopic_id\x18\x01 \x01(\x03R\atopicId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\x03R\tmessageId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\"=\n" +
	"\bNodeInfo\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"/\n" +
	"\fUserResponse\x12\x1f\n" +
	"\x04user\x18\x01 \x03(\v2\v.proto.UserR\x04user\"'\n" +
	"\x11CreateUserRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"(\n" +
	"\x12CreateTopicRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\\\n" +
	"\x12PostMessageRequest\x12\x19\n" +
	"\btopic_id\x18\x01 \x01(\x03R\atopicId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\"g\n" +
	"\x12LikeMessageRequest\x12\x19\n" +
	"\btopic_id\x18\x01 \x01(\x03R\atopicId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\x03R\tmessageId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\":\n" +
	"\x12ListTopicsResponse\x12$\n" +
	"\x06topics\x18\x01 \x03(\v2\f.proto.TopicR\x06topics\"m\n" +
	"\x12GetMessagesRequest\x12\x19\n" +
	"\btopic_id\x18\x01 \x01(\x03R\atopicId\x12&\n" +
	"\x0ffrom_message_id\x18\x02 \x01(\x03R\rfromMessageId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"A\n" +
	"\x13GetMessagesResponse\x12*\n" +
	"\bmessages\x18\x01 \x03(\v2\x0e.proto.MessageR\bmessages\"\x9c\x01\n" +
	"\x15SubscribeTopicRequest\x12\x19\n" +
	"\btopic_id\x18\x01 \x03(\x03R\atopicId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12&\n" +
	"\x0ffrom_message_id\x18\x03 \x01(\x03R\rfromMessageId\x12'\n" +
	"\x0fsubscribe_token\x18\x04 \x01(\tR\x0esubscribeToken\"M\n" +
	"\x17SubscriptionNodeRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\btopic_id\x18\x02 \x03(\x03R\atopicId\"h\n" +
	"\x18SubscriptionNodeResponse\x12'\n" +
	"\x0fsubscribe_token\x18\x01 \x01(\tR\x0esubscribeToken\x12#\n" +
	"\x04node\x18\x02 \x01(\v2\x0f.proto.NodeInfoR\x04node\"\xb7\x01\n" +
	"\fMessageEvent\x12'\n" +
	"\x0fsequence_number\x18\x01 \x01(\x03R\x0esequenceNumber\x12\x1d\n" +
	"\x02op\x18\x02 \x01(\x0e2\r.proto.OpTypeR\x02op\x12(\n" +
	"\amessage\x18\x03 \x01(\v2\x0e.proto.MessageR\amessage\x125\n" +
	"\bevent_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aeventAt\"E\n" +
	"\x11NewServerResponse\x120\n" +
	"\vsync_server\x18\x01 \x01(\v2\x0f.proto.NodeInfoR\n" +
	"syncServer\"E\n" +
	"\x11NextServerRequest\x120\n" +
	"\vnext_server\x18\x01 \x01(\v2\x0f.proto.NodeInfoR\n" +
	"nextServer\"B\n" +
	"\x10NewServerRequest\x12.\n" +
	"\n" +
	"new_server\x18\x01 \x01(\v2\x0f.proto.NodeInfoR\tnewServer\"$\n" +
	"\x0eSetTailRequest\x12\x12\n" +
	"\x04tail\x18\x01 \x01(\bR\x04tail\"$\n" +
	"\x0eSetHeadRequest\x12\x12\n" +
	"\x04head\x18\x01 \x01(\bR\x04head\"c\n" +
	"\x17GetClusterStateResponse\x12#\n" +
	"\x04head\x18\x01 \x01(\v2\x0f.proto.NodeInfoR\x04head\x12#\n" +
	"\x04tail\x18\x02 \x01(\v2\x0f.proto.NodeInfoR\x04tail\"5\n" +
	"\x0fSyncUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"6\n" +
	"\x10SyncTopicRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"l\n" +
	"\x12SyncMessageRequest\x12\x19\n" +
	"\btopic_id\x18\x01 \x01(\x03R\atopicId\x12\x17\n" +
	"\apost_id\x18\x02 \x01(\x03R\x06postId\x12\"\n" +
	"\x04post\x18\x03 \x01(\v2\x0e.proto.MessageR\x04post\"d\n" +
	"\x0fSyncLikeRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x03R\tmessageId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x19\n" +
	"\btopic_id\x18\x03 \x01(\x03R\atopicId\"\xa5\x01\n" +
	"\n" +
	"TopicPosts\x12\x19\n" +
	"\btopic_id\x18\x01 \x01(\x03R\atopicId\x122\n" +
	"\x05posts\x18\x02 \x03(\v2\x1c.proto.TopicPosts.PostsEntryR\x05posts\x1aH\n" +
	"\n" +
	"PostsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12$\n" +
	"\x05value\x18\x02 \x01(\v2\x0e.proto.MessageR\x05value:\x028\x01\"Q\n" +
	"\x0eTopicPostsList\x12\x19\n" +
	"\btopic_id\x18\x01 \x01(\x03R\atopicId\x12$\n" +
	"\x05posts\x18\x02 \x03(\v2\x0e.proto.MessageR\x05posts\"E\n" +
	"\tUserLikes\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vmessage_ids\x18\x02 \x03(\x03R\n" +
	"messageIds\"L\n" +
	"\x10SubscriptionData\x12\x1d\n" +
	"\n" +
	"topic_name\x18\x01 \x01(\tR\ttopicName\x12\x19\n" +
	"\btopic_id\x18\x02 \x01(\x03R\atopicId\"n\n" +
	"\x11UserSubscriptions\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12=\n" +
	"\rsubscriptions\x18\x02 \x03(\v2\x17.proto.SubscriptionDataR\rsubscriptions\"\xd6\x04\n" +
	"\x12SyncServerResponse\x12:\n" +
	"\x05users\x18\x01 \x03(\v2$.proto.SyncServerResponse.UsersEntryR\x05users\x12\x1d\n" +
	"\n" +
	"user_index\x18\x02 \x01(\x03R\tuserIndex\x12=\n" +
	"\x06topics\x18\x03 \x03(\v2%.proto.SyncServerResponse.TopicsEntryR\x06topics\x12\x1f\n" +
	"\vtopic_index\x18\x04 \x01(\x03R\n" +
	"topicIndex\x124\n" +
	"\ftopics_posts\x18\x05 \x03(\v2\x11.proto.TopicPostsR\vtopicsPosts\x12A\n" +
	"\x11topics_posts_list\x18\x06 \x03(\v2\x15.proto.TopicPostsListR\x0ftopicsPostsList\x12\x1d\n" +
	"\n" +
	"post_index\x18\a \x01(\x03R\tpostIndex\x12/\n" +
	"\n" +
	"user_likes\x18\b \x03(\v2\x10.proto.UserLikesR\tuserLikes\x12G\n" +
	"\x12user_subscriptions\x18\t \x03(\v2\x18.proto.UserSubscriptionsR\x11userSubscriptions\x1a8\n" +
	"\n" +
	"UsersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1a9\n" +
	"\vTopicsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01*\"\n" +
	"\x06OpType\x12\v\n" +
	"\aOP_POST\x10\x00\x12\v\n" +
	"\aOP_LIKE\x10\x012\xd2\x05\n" +
	"\fMessageBoard\x123\n" +
	"\n" +
	"CreateUser\x12\x18.proto.CreateUserRequest\x1a\v.proto.User\x126\n" +
	"\vCreateTopic\x12\x19.proto.CreateTopicRequest\x1a\f.proto.Topic\x128\n" +
	"\vPostMessage\x12\x19.proto.PostMessageRequest\x1a\x0e.proto.Message\x128\n" +
	"\vLikeMessage\x12\x19.proto.LikeMessageRequest\x1a\x0e.proto.Message\x12R\n" +
	"\x0fGetSubscription\x12\x1e.proto.SubscriptionNodeRequest\x1a\x1f.proto.SubscriptionNodeResponse\x127\n" +
	"\bGetUsers\x12\x16.google.protobuf.Empty\x1a\x13.proto.UserResponse\x12?\n" +
	"\n" +
	"ListTopics\x12\x16.google.protobuf.Empty\x1a\x19.proto.ListTopicsResponse\x12D\n" +
	"\vGetMessages\x12\x19.proto.GetMessagesRequest\x1a\x1a.proto.GetMessagesResponse\x12E\n" +
	"\x0eSubscribeTopic\x12\x1c.proto.SubscribeTopicRequest\x1a\x13.proto.MessageEvent0\x01\x12N\n" +
	"\x14GenerateSubscription\x12\x1e.proto.SubscriptionNodeRequest\x1a\x16.google.protobuf.Empty\x126\n" +
	"\x04Ping\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty2\xe7\x03\n" +
	"\fControlPlane\x12I\n" +
	"\x0fGetClusterState\x12\x16.google.protobuf.Empty\x1a\x1e.proto.GetClusterStateResponse\x12=\n" +
	"\vControlPing\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x128\n" +
	"\aSetTail\x12\x15.proto.SetTailRequest\x1a\x16.google.protobuf.Empty\x128\n" +
	"\aSetHead\x12\x15.proto.SetHeadRequest\x1a\x16.google.protobuf.Empty\x12>\n" +
	"\tNewServer\x12\x17.proto.NewServerRequest\x1a\x18.proto.NewServerResponse\x12A\n" +
	"\rSetNextServer\x12\x18.proto.NextServerRequest\x1a\x16.google.protobuf.Empty\x12V\n" +
	"\x13GetSubscriptionNode\x12\x1e.proto.SubscriptionNodeRequest\x1a\x1f.proto.SubscriptionNodeResponse2\xff\x02\n" +
	"\bsyncData\x12:\n" +
	"\bSyncUser\x12\x16.proto.SyncUserRequest\x1a\x16.google.protobuf.Empty\x12<\n" +
	"\tSyncTopic\x12\x17.proto.SyncTopicRequest\x1a\x16.google.protobuf.Empty\x12@\n" +
	"\vSyncMessage\x12\x19.proto.SyncMessageRequest\x1a\x16.google.protobuf.Empty\x12:\n" +
	"\bSyncLike\x12\x16.proto.SyncLikeRequest\x1a\x16.google.protobuf.Empty\x12:\n" +
	"\bSyncPing\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12?\n" +
	"\n" +
	"SyncServer\x12\x16.google.protobuf.Empty\x1a\x19.proto.SyncServerResponseB\x12Z\x10/razpravljalnicab\x06proto3"

var (
	file_proto_razpravljalnica_proto_rawDescOnce sync.Once
	file_proto_razpravljalnica_proto_rawDescData []byte
)

func file_proto_razpravljalnica_proto_rawDescGZIP() []byte {
	file_proto_razpravljalnica_proto_rawDescOnce.Do(func() {
		file_proto_razpravljalnica_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_razpravljalnica_proto_rawDesc), len(file_proto_razpravljalnica_proto_rawDesc)))
	})
	return file_proto_razpravljalnica_proto_rawDescData
}

var file_proto_razpravljalnica_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_razpravljalnica_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_proto_razpravljalnica_proto_goTypes = []any{
	(OpType)(0),                      // 0: proto.OpType
	(*User)(nil),                     // 1: proto.User
	(*Topic)(nil),                    // 2: proto.Topic
	(*Message)(nil),                  // 3: proto.Message
	(*Like)(nil),                     // 4: proto.Like
	(*NodeInfo)(nil),                 // 5: proto.NodeInfo
	(*UserResponse)(nil),             // 6: proto.UserResponse
	(*CreateUserRequest)(nil),        // 7: proto.CreateUserRequest
	(*CreateTopicRequest)(nil),       // 8: proto.CreateTopicRequest
	(*PostMessageRequest)(nil),       // 9: proto.PostMessageRequest
	(*LikeMessageRequest)(nil),       // 10: proto.LikeMessageRequest
	(*ListTopicsResponse)(nil),       // 11: proto.ListTopicsResponse
	(*GetMessagesRequest)(nil),       // 12: proto.GetMessagesRequest
	(*GetMessagesResponse)(nil),      // 13: proto.GetMessagesResponse
	(*SubscribeTopicRequest)(nil),    // 14: proto.SubscribeTopicRequest
	(*SubscriptionNodeRequest)(nil),  // 15: proto.SubscriptionNodeRequest
	(*SubscriptionNodeResponse)(nil), // 16: proto.SubscriptionNodeResponse
	(*MessageEvent)(nil),             // 17: proto.MessageEvent
	(*NewServerResponse)(nil),        // 18: proto.NewServerResponse
	(*NextServerRequest)(nil),        // 19: proto.NextServerRequest
	(*NewServerRequest)(nil),         // 20: proto.NewServerRequest
	(*SetTailRequest)(nil),           // 21: proto.SetTailRequest
	(*SetHeadRequest)(nil),           // 22: proto.SetHeadRequest
	(*GetClusterStateResponse)(nil),  // 23: proto.GetClusterStateResponse
	(*SyncUserRequest)(nil),          // 24: proto.SyncUserRequest
	(*SyncTopicRequest)(nil),         // 25: proto.SyncTopicRequest
	(*SyncMessageRequest)(nil),       // 26: proto.SyncMessageRequest
	(*SyncLikeRequest)(nil),          // 27: proto.SyncLikeRequest
	(*TopicPosts)(nil),               // 28: proto.TopicPosts
	(*TopicPostsList)(nil),           // 29: proto.TopicPostsList
	(*UserLikes)(nil),                // 30: proto.UserLikes
	(*SubscriptionData)(nil),         // 31: proto.SubscriptionData
	(*UserSubscriptions)(nil),        // 32: proto.UserSubscriptions
	(*SyncServerResponse)(nil),       // 33: proto.SyncServerResponse
	nil,                              // 34: proto.TopicPosts.PostsEntry
	nil,                              // 35: proto.SyncServerResponse.UsersEntry
	nil,                              // 36: proto.SyncServerResponse.TopicsEntry
	(*timestamppb.Timestamp)(nil),    // 37: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),            // 38: google.protobuf.Empty
}
var file_proto_razpravljalnica_proto_depIdxs = []int32{
	37, // 0: proto.Message.created_at:type_name -> google.protobuf.Timestamp
	1,  // 1: proto.UserResponse.user:type_name -> proto.User
	2,  // 2: proto.ListTopicsResponse.topics:type_name -> proto.Topic
	3,  // 3: proto.GetMessagesResponse.messages:type_name -> proto.Message
	5,  // 4: proto.SubscriptionNodeResponse.node:type_name -> proto.NodeInfo
	0,  // 5: proto.MessageEvent.op:type_name -> proto.OpType
	3,  // 6: proto.MessageEvent.message:type_name -> proto.Message
	37, // 7: proto.MessageEvent.event_at:type_name -> google.protobuf.Timestamp
	5,  // 8: proto.NewServerResponse.sync_server:type_name -> proto.NodeInfo
	5,  // 9: proto.NextServerRequest.next_server:type_name -> proto.NodeInfo
	5,  // 10: proto.NewServerRequest.new_server:type_name -> proto.NodeInfo
	5,  // 11: proto.GetClusterStateResponse.head:type_name -> proto.NodeInfo
	5,  // 12: proto.GetClusterStateResponse.tail:type_name -> proto.NodeInfo
	3,  // 13: proto.SyncMessageRequest.post:type_name -> proto.Message
	34, // 14: proto.TopicPosts.posts:type_name -> proto.TopicPosts.PostsEntry
	3,  // 15: proto.TopicPostsList.posts:type_name -> proto.Message
	31, // 16: proto.UserSubscriptions.subscriptions:type_name -> proto.SubscriptionData
	35, // 17: proto.SyncServerResponse.users:type_name -> proto.SyncServerResponse.UsersEntry
	36, // 18: proto.SyncServerResponse.topics:type_name -> proto.SyncServerResponse.TopicsEntry
	28, // 19: proto.SyncServerResponse.topics_posts:type_name -> proto.TopicPosts
	29, // 20: proto.SyncServerResponse.topics_posts_list:type_name -> proto.TopicPostsList
	30, // 21: proto.SyncServerResponse.user_likes:type_name -> proto.UserLikes
	32, // 22: proto.SyncServerResponse.user_subscriptions:type_name -> proto.UserSubscriptions
	3,  // 23: proto.TopicPosts.PostsEntry.value:type_name -> proto.Message
	7,  // 24: proto.MessageBoard.CreateUser:input_type -> proto.CreateUserRequest
	8,  // 25: proto.MessageBoard.CreateTopic:input_type -> proto.CreateTopicRequest
	9,  // 26: proto.MessageBoard.PostMessage:input_type -> proto.PostMessageRequest
	10, // 27: proto.MessageBoard.LikeMessage:input_type -> proto.LikeMessageRequest
	15, // 28: proto.MessageBoard.GetSubscription:input_type -> proto.SubscriptionNodeRequest
	38, // 29: proto.MessageBoard.GetUsers:input_type -> google.protobuf.Empty
	38, // 30: proto.MessageBoard.ListTopics:input_type -> google.protobuf.Empty
	12, // 31: proto.MessageBoard.GetMessages:input_type -> proto.GetMessagesRequest
	14, // 32: proto.MessageBoard.SubscribeTopic:input_type -> proto.SubscribeTopicRequest
	15, // 33: proto.MessageBoard.GenerateSubscription:input_type -> proto.SubscriptionNodeRequest
	38, // 34: proto.MessageBoard.Ping:input_type -> google.protobuf.Empty
	38, // 35: proto.ControlPlane.GetClusterState:input_type -> google.protobuf.Empty
	38, // 36: proto.ControlPlane.ControlPing:input_type -> google.protobuf.Empty
	21, // 37: proto.ControlPlane.SetTail:input_type -> proto.SetTailRequest
	22, // 38: proto.ControlPlane.SetHead:input_type -> proto.SetHeadRequest
	20, // 39: proto.ControlPlane.NewServer:input_type -> proto.NewServerRequest
	19, // 40: proto.ControlPlane.SetNextServer:input_type -> proto.NextServerRequest
	15, // 41: proto.ControlPlane.GetSubscriptionNode:input_type -> proto.SubscriptionNodeRequest
	24, // 42: proto.syncData.SyncUser:input_type -> proto.SyncUserRequest
	25, // 43: proto.syncData.SyncTopic:input_type -> proto.SyncTopicRequest
	26, // 44: proto.syncData.SyncMessage:input_type -> proto.SyncMessageRequest
	27, // 45: proto.syncData.SyncLike:input_type -> proto.SyncLikeRequest
	38, // 46: proto.syncData.SyncPing:input_type -> google.protobuf.Empty
	38, // 47: proto.syncData.SyncServer:input_type -> google.protobuf.Empty
	1,  // 48: proto.MessageBoard.CreateUser:output_type -> proto.User
	2,  // 49: proto.MessageBoard.CreateTopic:output_type -> proto.Topic
	3,  // 50: proto.MessageBoard.PostMessage:output_type -> proto.Message
	3,  // 51: proto.MessageBoard.LikeMessage:output_type -> proto.Message
	16, // 52: proto.MessageBoard.GetSubscription:output_type -> proto.SubscriptionNodeResponse
	6,  // 53: proto.MessageBoard.GetUsers:output_type -> proto.UserResponse
	11, // 54: proto.MessageBoard.ListTopics:output_type -> proto.ListTopicsResponse
	13, // 55: proto.MessageBoard.GetMessages:output_type -> proto.GetMessagesResponse
	17, // 56: proto.MessageBoard.SubscribeTopic:output_type -> proto.MessageEvent
	38, // 57: proto.MessageBoard.GenerateSubscription:output_type -> google.protobuf.Empty
	38, // 58: proto.MessageBoard.Ping:output_type -> google.protobuf.Empty
	23, // 59: proto.ControlPlane.GetClusterState:output_type -> proto.GetClusterStateResponse
	38, // 60: proto.ControlPlane.ControlPing:output_type -> google.protobuf.Empty
	38, // 61: proto.ControlPlane.SetTail:output_type -> google.protobuf.Empty
	38, // 62: proto.ControlPlane.SetHead:output_type -> google.protobuf.Empty
	18, // 63: proto.ControlPlane.NewServer:output_type -> proto.NewServerResponse
	38, // 64: proto.ControlPlane.SetNextServer:output_type -> google.protobuf.Empty
	16, // 65: proto.ControlPlane.GetSubscriptionNode:output_type -> proto.SubscriptionNodeResponse
	38, // 66: proto.syncData.SyncUser:output_type -> google.protobuf.Empty
	38, // 67: proto.syncData.SyncTopic:output_type -> google.protobuf.Empty
	38, // 68: proto.syncData.SyncMessage:output_type -> google.protobuf.Empty
	38, // 69: proto.syncData.SyncLike:output_type -> google.protobuf.Empty
	38, // 70: proto.syncData.SyncPing:output_type -> google.protobuf.Empty
	33, // 71: proto.syncData.SyncServer:output_type -> proto.SyncServerResponse
	48, // [48:72] is the sub-list for method output_type
	24, // [24:48] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_proto_razpravljalnica_proto_init() }
func file_proto_razpravljalnica_proto_init() {
	if File_proto_razpravljalnica_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_razpravljalnica_proto_rawDesc), len(file_proto_razpravljalnica_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_proto_razpravljalnica_proto_goTypes,
		DependencyIndexes: file_proto_razpravljalnica_proto_depIdxs,
		EnumInfos:         file_proto_razpravljalnica_proto_enumTypes,
		MessageInfos:      file_proto_razpravljalnica_proto_msgTypes,
	}.Build()
	File_proto_razpravljalnica_proto = out.File
	file_proto_razpravljalnica_proto_goTypes = nil
	file_proto_razpravljalnica_proto_depIdxs = nil
}
